### ISSUE TITLE
Lab03: Startup: AccountEndpint is missing

### ISSUE THREAD

**Issue by ThomasWendrock** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#126]
## Location
- Course: AZ-203
- Exercise: 03
- Task: 04
- Step[s]: 04

## Description

When starting the web app, there occurs an error, because the Cosmos ConnectionString (Account Endpoint) is missing.
Stacktrace:
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.ArgumentException: The connection string is missing a required property: AccountEndpoint
   at Microsoft.Azure.Cosmos.CosmosClientOptions.GetValueFromConnectionString(String connectionString, String keyName)
   at Microsoft.Azure.Cosmos.CosmosClient..ctor(String connectionString, CosmosClientOptions clientOptions)
   at AdventureWorks.Context.AdventureWorksCosmosContext..ctor(String connectionString, String database, String container) in C:\Develop\Schulung\AZ-203-DevelopingSolutionsforMicrosoftAzure\Allfiles\Labs\03\Solution\AdventureWorks\AdventureWorks.Context\AdventureWorksCosmosContext.cs:line 17
...

But there seem to be an "bigger" problem, because it's not consistent to use Cosmos DB here, when Azure SQL Server should be used first. Additionally, when adding the CosmosDb-ConnectionString like described in Exercise 4/Task 2/Step 6, there occurs another error on Startup saying that the Cosmos DB Owner is missing.

## Repro steps

1.
1.
1.

**Comment by seesharprun** [comment]
It looks like we had a code snippet that omitted connection setting that were irrelevant to the current step.

The code snippet looked like this:

```
"ConnectionStrings": {
    "AdventureWorksSqlContext": "",
    ...
},
```

And the actual configuration file looked like this:

```
"ConnectionStrings": {
    "AdventureWorksSqlContext": "",
    "AdventureWorksCosmosContext": "",
    "AdventureWorksRedisContext": ""
},
```

It looks like you may have copy+paste the code snippet with omissions. This caused a build failure because the cosmos & redis settings are required to exist even though they aren't in use yet in the lab.

We updated the lab instructions to include the full configuration code with no omissions to avoid this issue in the future.

This change is in 95df6177980cba1e91798060ade2885271cbcd3c
