### ISSUE TITLE
Lab 3: .NET Core 2.2 SDK is end of life.

### ISSUE THREAD

**Issue by tinodo** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#128]
This problem does NOT relate to the LAB VM, but occurs when students use their own machines. Therefore, this might not be an urgent issue, but something for the backlog....

These are the steps to reproduce:

* Create a new Windows 10 VM and install the latest .NET Core SDK (currently 3.1.1).
(Either through the `dotnet-install.ps1` or by downloading and running the MSI installer)
* Download the Lab 3 AdventureWorks code.
* Try to compile with `dotnet build`

This will fail:

`C:\Users\currentuser\.nuget\packages\microsoft.aspnetcore.razor.design\2.2.0\build\netstandard2.0\Microsoft.AspNetCore.Razor.Design.CodeGeneration.targets(79,5): error : rzc discover exited with code -2147450730. [C:\Users\currentuser\Desktop\AdventureWorks\AdventureWorks.Web\AdventureWorks.Web.csproj]`
`The build failed. Fix the build errors and run again.`

The error can be fixed by installing the .NET Core SDK 2.2. (Although 3.1.1 is already installed!)
However, this 2.2 version is end of life and later versions of the .NET Core SDK *should* be able to build solutions targeting a previous framework version.

More information on End of Life of 2.2:
[https://dotnet.microsoft.com/download/dotnet-core](https://dotnet.microsoft.com/download/dotnet-core)

More information on how newer versions of the SDK should (most of the time) be able to be used against projects targeting an older framework:
[https://docs.microsoft.com/en-us/dotnet/core/versions/selection](https://docs.microsoft.com/en-us/dotnet/core/versions/selection)

Should you be able to build it using a newer version of the SDK (which will happen if the older version was once installed), you cannot run the Web project:

`It was not possible to find any compatible framework version`
`The framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.`
`  - The following frameworks were found:`
`      3.1.1 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]`
``
`You can resolve the problem by installing the specified framework and/or SDK.`
``
`The specified framework can be found at:`
`  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=2.2.0&arch=x64&rid=win10-x64`

Although not very urgent at this point, but it would be great to have the project build and run with a later .NET Core SDK installed and remove the hard .NET Core SDK 2.2 dependency.

Thanks!

**Comment by seesharprun** [comment]
Officially, the labs are built and tested to run within an Authorized Lab Host (ALH). That is the supported scenario. The ALHs have lab VMs running .NET Core 2.2.

In retrospect, we should have built the labs and VM to run on .NET Core 2.1 which was an LTS version. This was an error we will correct in future courseware.

While students can attempt to run labs locally, we do not provide support for that scenario. That would be an "at your own risk" venture.

As far as .NET versions, simply updating the labs to .NET Core 3.1 will not solve the problem permanently. In November, when .NET 5 is released, you will run into incompatibility issues again because many students will have downloaded alpha/beta builds of .NET 5 to their local machine. We provide a lab virtual machine so we can "freeze" the .NET version in time and ensure that the labs work consistently through the lifetime of the course.

In the next iteration of ILT that maps to the Azure Developer Associate certification, we will have labs that run on .NET Core 3.1, a LTS version of .NET. Please refer to the Courseware Title Plan, made available to MCTs, to see the relevant details for that course.

This course's labs will not be updated beyond .NET Core 2.2 to ensure that they continue to function correctly in the existing lab VMs that are hosted by ALHs.
