### ISSUE TITLE
Use of Azure Cache for Redis in Lab 3

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#131]
Students only get to learn about this Azure service in T05. As such, it would seem to make sense to move any Redis-related exercises from Lab 3 to Lab 5.

**Comment by seesharprun** [comment]
This change has been implemented in the course that will replace this course.

You can refer to the courseware title plan on MCT central to see the release date of the next course.

Since we are so close to the next release, we won't be able to make any major updates to the current labs and are in a "fix-only" mode right now.
