### ISSUE TITLE
T03 Build and deployment steps missing?

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#6]
# Module: 03
#### Step: 00

Description of issue
The lab ends without building the solution and deploying it to azure. Are these steps missing?

Repro steps:

1.
1.
1.

**Comment by seesharprun** [comment]
> I'm one of the MCTs who helped to author this lab.

No steps are missing, the lab was designed to have the students write the code but not build or deploy the solution. Everything is in the current version of the lab and it passed functional test.

**A bit of background**: A version of this polyglot lab has existed in multiple courses with updates and enhancements over the years. In previous versions of the lab, students would have a hard time building and deploying the solution. It makes sense when you look at how many data services and projects exist in this solution. If you mess up deploying even a single piece, you wouldn't get the expected result. In practice, we found that students spent 75% of the lab time deploying code versus writing code and that was not the intention of a developer course.

*A design decision was made during lab development to have the lab focus on students writing code for the services rather than deploying that code.*

If you disagree with this decision, this is the right place to discuss that. Adding an additional exercise wouldn't take too long but I would need a few questions answered:

1. Do you just want to just build the code to validate the lab or do you also want to deploy it?
1. If you wish to deploy the code, do you want the student to perform manual deployment of every service or take a shortcut (ARM template)?
1. How should the lab end? Should it end when the code is deployed or when the student visits a test webpage?
1. Should there be additional validation steps? For example, if the student adds a registration, should we go to Azure Cosmos DB to check the registration?

I am going to wait a couple of days to let a few MCTs chime in on those questions. Once they are answered, I will open a PR to add an additional exercise so we an all track the progress in real time.

**Comment by molenaar** [comment]
It would be nice if the code at least builds in visual studio. 
I can replace the wrong pieces of code:
//var task = new ContextInitializer().InitializeAsync(eventsContext, registrationsContext);
var task = new ContextInitializer().InitializeAsync(eventsContext);
and it builds fine.

However if you have to change the code in the events.worker project in Exercise 5 and call the ProcessStorageMessage method instead of the ProcessHttpRequestMessage method, you should expect that the ProcessHttpRequestMessage method has to be changed to.
After Exercise 5 the lab suddenly stops and the student ends up with code that doesn't compile.

1. Do you just want to just build the code to validate the lab or do you also want to deploy it?
Yes, my students expect a working lab. They have spent a lot of time building an environment and writing code. And at the end it doesn't work.

> 2. If you wish to deploy the code, do you want the student to perform manual deployment of every service or take a shortcut (ARM template)?

Could be an optional task left to the student. They deployed the web and api in the lab of book 2. So they should be able to deploy it.

> 3. How should the lab end? Should it end when the code is deployed or when the student visits a test webpage?

No opinion. At least that it builds an runs locally. If the design decision is the focus on students writing code, I hope it is writing code that **works**.

>Should there be additional validation steps? For example, if the student adds a registration, should we go to Azure Cosmos DB to check the registration?
That should be nice but optional.

I also hope more opinions of other MCTs.

**Comment by seesharprun** [comment]
Thanks for the feedback.

I can minimize the time spent deploying by having the student deploy an ARM template that includes Cosmos, SQL and various App Services. We can then have the students "push" every project to the various App Service instances as part of the lab instructions.

I just created a pull request where you can track the work in real time. In the PR, I will create an exercise with the requested steps. Since this will take some time, any other MCT can jump in and leave feedback if anyone wants to change course mid-PR.

**Comment by fincooper** [comment]
>     3\. How should the lab end? Should it end when the code is deployed or when the student visits a test webpage?
> 
>     4\. Should there be additional validation steps? For example, if the student adds a registration, should we go to Azure Cosmos DB to check the registration?
> 
> 
> I am going to wait a couple of days to let a few MCTs chime in on those questions.



> * Do you just want to just build the code to validate the lab or do you also want to deploy it?
> 
> * If you wish to deploy the code, do you want the student to perform manual deployment of every service or take a shortcut (ARM template)?
> 
> * How should the lab end? Should it end when the code is deployed or when the student visits a test webpage?
> 
> * Should there be additional validation steps? For example, if the student adds a registration, should we go to Azure Cosmos DB to check the registration?

Thanks for the backgrounder, Sidney! 

The current ending of the lab created confusion in my class. The simplest way to end the lab would be to finish the coding part and make the VS solution buildable. This really feels like a minimum requirement. To make this lab more usable as an Azure lab, I would love to see this ready for being deployed. ARM templates would be a) quick to implement without unnecessary long completion steps b) helpful in driving the students towards proper deployment practices in Azure development.
