### ISSUE TITLE
Bug in Lab 6 - Exercise 2 - Task 3 - Step 15

### ISSUE THREAD

**Issue by davidokeyode** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#65]
## Location

- Course: AZ-203-DevelopingSolutionsforMicrosoftAzure (Lab 6)
- Exercise: 02
- Task: 03
- Step[s]: 15

## Description

Description of issue
Bug in the step requires to click the "once" button and click back
https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-203_06_lab_ak.md

## Repro steps

1. When doing step 15, the submit button is greyed out until the "once" option is selected and then you select the "custom" option afterwards.

**Comment by seesharprun** [comment]
> I'm updating each of the open issues this week to let you know that there was a small delay in the latest round of updates. They should be ready about one week later than originally anticipated.

**Comment by seesharprun** [comment]
We did notice a portal bug where you were forced to select and then unselect the **Track deletions** and **Once/Custom** fields. This is due to a portal bug. A note has been added to the instructions.

Instructions are updated in [Version 20190822.03](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190822.03).
