### ISSUE TITLE
AdventureWorks.Migrate project uses deprecated version of .Net Core (2.0)

### ISSUE THREAD

**Issue by bergmeister** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#68]
## Location

- Course: `Az-203`
- Exercise: Lab 03
- Task: NA
- Step[s]: NA

## Description

.Net Core 2.0 is not supported any more but the solution below uses it:

https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/blob/81ba8dddccc07410add02fdcf8da482428a6dd18/Allfiles/Labs/03/Solution/AdventureWorks/AdventureWorks.Migrate/AdventureWorks.Migrate.csproj

**Comment by seesharprun** [comment]
Good catch. When I wrote the lab, I am running .NET 5-alpha on my authoring machines and manually downgrade the projects to .NET Core 2.x.

I downgraded this a bit too far 😆 .

Fixed in [Version 20190821.01](https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/releases/tag/v20190821.01)

**Comment by bergmeister** [comment]
Wow, that was a quick fix. thanks. Have you tested, it actually still compiles and runs fine?
One last nit that I've seen in the csproj is the usage of C# preview:
```
<LangVersion>preview</LangVersion>
```

**Comment by seesharprun** [comment]
I downloaded the solution file locally and built it using the old .NET Core version and then the new version.

The ``LangVersion`` project setting is a necessary evil right now. We implement is using this command:

```
dotnet new console --name AdventureWorks.Migrate --langVersion preview
```

It's used to make our code easier to read/write by using two C# language features not available in vanilla .NET Core 2.x:
- The [asynchronous Main entry point](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-1#async-main) feature introduced in C# 7.1. The Cosmos SDK is async by default and this makes setting up the ``Program`` class much easier. Fun fact: This feature only requires the ``latest`` language version.
- The [using declarations](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations) feature introduced in C# 8. In testing, I found that people get tripped up a lot over putting code in using blocks. With this feature, the using block is inferred and it makes things much easier to write. This feature requires the ``preview`` language version.

All of this will be resolved when we move to .NET Core 3.x (or preferably .NET 5).

**Comment by bergmeister** [comment]
Hmm, I see. My (opinionated) point of view though is that although the new `using` statement is more elegant for experience programmers, the  explicit braces would allow people to better understand/see when something is disposed. Also, if they 'learn' this as syntax, they might be surprised that this actually does not work out of the box in a different project, which could cause confusion and frustration. I'd advocate to not use preview features for educational purposes unless they are absolutely necessary as the target is to learn  new concepts. Learning and using upcoming C# might be fun but I rather see them as a distraction and not the right time to use/show them although it's always good to learn new things.... Just my 2 pence 
I like the deep thought/touch that you've put into it though :-)

**Comment by seesharprun** [comment]
The current instructions are a compromise.

We create the ``DocumentClient`` and ``DbContext`` instances and don't wrap them in a ``using`` statement at all.

This allows us to avoid the problem we are having with using blocks all together.

Unfortunately, it's not a best practice.

In this example, I take the opinionated stance that we should let the C# class teach developers the various permutations of the language syntax rather than this (Azure Developer) class.
