### ISSUE TITLE
Excercise 4 throws exception on systems with decimal symbol different than dot

### ISSUE THREAD

**Issue by michal-madrzyk** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#70]
## Location

- Course: 03
- Exercise: Exercise 4: Migrating SQL data to Azure Cosmos DB
- Task: Task 1: Create migration project
- Step[s]: 07

## Description

Using Microsoft.Azure.Cosmos package in version 3.0.0 is causing data migration to fail (exception is thrown from Double.Parse method).

## Repro steps

1. Use in system regional settings commas (,) as decimal symbol
2. Follow labs instruction as usual (using version 3.0.0 of Microsoft.Azure.Cosmos package)

## Solution

Version 3.0.0 uses wrong culture info. It has been fixed in version 3.1.0. Please fix it in lab instructions.

**Comment by seesharprun** [comment]
I am having a hard time recreating this. Which Authorized Lab Host (ALH) are you using? I want to test in their environment to validate the issue.

**Comment by seesharprun** [comment]
I was unable to find an ALH that used a VM with culture info that caused this bug. If you do find one, please re-open this issue with the name of the ALH so I can verify the bug.

**Comment by tinodo** [comment]
I have seen this issue as well. When using the Labs from your own machine, there might be localization issue. You can fix this is in the startup class by forcing the currentculture to be en-US. That fixes these NumberFormatExceptions.
It won't happen when running from the lab VM, since that one is set to en-US. 
By adding this single line of code to the lab, we would mitigate the entire issue.
