### ISSUE TITLE
Target framework issue

### ISSUE THREAD

**Issue by krisrajzlive** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#73]
https://github.com/MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure/blob/master/Instructions/Labs/AZ-203_03_lab_ak.md

- Course: AZ-203
- Exercise: 03
- Task: 01
- Step[s]: dotnet build

## Description

Getting error message when I try running the command;
dotnet build

C:\Program Files\dotnet\sdk\2.1.602\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [C:\Users\krisrajz\source\repos\MicrosoftLearning\AZ-203-DevelopingSolutionsforMicrosoftAzure\Allfiles\Labs\03\Solution\AdventureWorks\AdventureWorks.Web\AdventureWorks.Web.csproj]
C:\Program Files\dotnet\sdk\2.1.602\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(150,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Standard 2.2.  Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.2. [C:\Users\krisrajz\source\repos\MicrosoftLearning\AZ-203-DevelopingSolutionsforMicrosoftAzure\Allfiles\Labs\03\Solution\AdventureWorks\AdventureWorks.Context\AdventureWorks.Context.csproj]
C:\Program Files\dotnet\sdk\2.1.602\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(150,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Standard 2.2.  Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.2. [C:\Users\krisrajz\source\repos\MicrosoftLearning\AZ-203-DevelopingSolutionsforMicrosoftAzure\Allfiles\Labs\03\Solution\AdventureWorks\AdventureWorks.Models\AdventureWorks.Models.csproj]

Tried opening the .csproj and changed target framework 2.1, still no respite. Any help would be much appreciated.

Thanks

**Comment by seesharprun** [comment]
Which ALH are you using? I want to test the VM image in their environment.

**Comment by krisrajzlive** [comment]
I am actually trying the lab on my laptop as creating new VM require many tools and frameworks to be installed and save time. My laptop is running on Windows 10 Pro, 16GB RAM, with both Visual Studio 2017 and VS Code. I was able to run rest of the previous labs except this one. Please let me know if you have any other questions.
Thanks.

**Comment by seesharprun** [comment]
## Officially

The labs are only supported within an Authorized Lab Hosting (ALH) environment. As a MCT, you should have free access to Microsoft Labs Online (MLO) to test the labs.

## Unofficially

The lab environment has .NET Core 2.2 installed. The error message you are receiving occurs when you have a newer version of .NET Core installed. If I had to hazard a guess, I would think that you installed .NET Core 3.0 on your local machine and are seeing the error message since .NET Core 3.0 is a newer version of .NET.

You can validate this by running the ``dotnet --version`` command on your machine. I ran that command on the lab VM in MLO and got back a response of ``2.2.103``.

**Comment by seesharprun** [comment]
I'm closing the issue since non-ALH environments are not supported. If the bug persists, you can re-open the issue.
