### ISSUE TITLE
Lab 4: Exercise 5: Can't open Cloud Shell

### ISSUE THREAD

**Issue by megaromb** [MicrosoftLearning/AZ-203-DevelopingSolutionsforMicrosoftAzure#90]
## Location

- Course: AZ-203-DevelopingSolutionsforMicrosoftAzure
- Exercise: 05
- Task: 01
- Step[s]: 01

Can't open Cloud Shell as it described in the step. Azure file share should exist before executing this step.

![2- no storage mounted](https://user-images.githubusercontent.com/4130842/68051474-21260080-fcf0-11e9-99fa-027be89b813e.png)
![1- welcome to cloud shell](https://user-images.githubusercontent.com/4130842/68051475-21be9700-fcf0-11e9-9f98-e0d532dcd995.png)

## Repro steps

1. "In the top navigation bar in the Azure Portal, select the Cloud Shell icon to open a new shell instance."

**Expected result**: Cloud Shell command prompt at the bottom of the portal should open
**Actual result**: (a) a message is displayed instead of the command prompt (see "1- welcome to cloud shell" image attached), (b) clicking either Bash or PowerShell opens a new dialog at the bottom of the portal (see "2- no storage mounted" image attached)

**Comment by seesharprun** [comment]
It looks like we errantly assumed that you would already have the Cloud Shell configured. Unfortunately, that's not the case if this lab is completed in isolation (which is a completely valid workflow).

Lab 1 has the instructions to configure the Cloud Shell but it seems like that should be copied to every lab that uses the shell to resolve this bug.

**Comment by seesharprun** [comment]
We are still talking internally about whether we want to replicate the instructions for each lab or assume a specific lab order.

**Comment by megaromb** [comment]
I'm unsure whether I should create another issue, because the context is similar to this one. I've started from lab 4, now I'm at 5th, and got error in Terminal window while deploying API project to Azure, "'az' is not recognized as the name of a cmdlet". It seems **Azure CLI should be a prerequisite** for the 5th and the other labs where CLI is used.

**Comment by seesharprun** [comment]
@megaromb, are you using the Bash or PowerShell version of the Cloud Shell?

**Comment by megaromb** [comment]
@seesharprun was about to use PowerShell, but anyway neither PS nor Bash did work - after clicking any option you'll get "No storage mounted" message.

**Comment by seesharprun** [comment]
@megaromb Can you share a screenshot? Just copy it and paste it into the text editor on GitHub. That will upload the screenshot.

I suspect your Cloud Shell was misconfigured since you started with Lab 4. If you continue to see that error message, you can run the ``clouddrive unmount`` to remove your storage association and "reset" the Cloud Shell to it's starting wizard. From there, just select **Bash** and the default storage options.

**Comment by seesharprun** [comment]
@megaromb I updated the lab instructions to break down how to configure the Cloud Shell in every single lab so it won't matter where you start in the labs.

This will officially close the original issue, but we can still figure out why your specific Cloud Shell instance is not working while the issue is closed.
